StudentGradebook/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gradebook.urls')),
    path('auth/', obtain_auth_token),
]

gradebook/urls.py
from django.db import router
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views
from .views import SemesterList, SemesterCreate, SemesterUpdate, SemesterDelete, SemesterDetail, CourseList, \
    CourseCreate, CourseUpdate, CourseDelete, CourseDetail, LecturerList, LecturerCreate, LecturerUpdate, \
    LecturerDelete, LecturerDetail, ClassList, ClassCreate, ClassUpdate, ClassDetail, ClassDelete, StudentList,  StudentCreate, StudentUpdate, StudentDetail, StudentDelete

router = DefaultRouter()
router.register('students', views.StudentViewSet, basename='student')
router.register('semesters', views.SemesterViewSet, basename='semester')
router.register('courses', views.CourseViewSet, basename='course')
router.register('lecturers', views.LecturerViewSet, basename='lecturer')
router.register('classes', views.ClassViewSet, basename='class')




urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.student_detail, name='view_student'),
    path("semester_list/", SemesterList.as_view(), name="semester_list"),
    path("semester_create/", SemesterCreate.as_view(), name="semester_create"),
    path("semester_update/<int:pk>/", SemesterUpdate.as_view(), name="semester_update"),
    path("semester_delete/<int:pk>/", SemesterDelete.as_view(), name="semester_delete"),
    path("semester_detail/<int:pk>/", SemesterDetail.as_view(), name="semester_detail"),
    path("course_list/", CourseList.as_view(), name="course_list"),
    path("course_create/", CourseCreate.as_view(), name="course_create"),
    path("course_update/<int:pk>/", CourseUpdate.as_view(), name="course_update"),
    path("course_delete/<int:pk>/", CourseDelete.as_view(), name="course_delete"),
    path("course_detail/<int:pk>/", CourseDetail.as_view(), name="course_detail"),
    path("lecturer_list/", LecturerList.as_view(), name="lecturer_list"),
    path("lecturer_create/", LecturerCreate.as_view(), name="lecturer_create"),
    path("lecturer_update/<int:pk>/", LecturerUpdate.as_view(), name="lecturer_update"),
    path("lecturer_delete/<int:pk>/", LecturerDelete.as_view(), name="lecturer_delete"),
    path("lecturer_detail/<int:pk>/", LecturerDetail.as_view(), name="lecturer_detail"),
    path("class_list/", ClassList.as_view(), name="class_list"),
    path("class_create/", ClassCreate.as_view(), name="class_create"),
    path("class_update/<int:pk>/", ClassUpdate.as_view(), name="class_update"),
    path("class_delete/<int:pk>/", ClassDelete.as_view(), name="class_delete"),
    path("class_detail/<int:pk>/", ClassDetail.as_view(), name="class_detail"),
    path("student_list/", StudentList.as_view(), name='student_list'),
    path("student_create/", StudentCreate.as_view(), name='student_create'),
    path("student_update/<int:pk>/", StudentUpdate.as_view(), name='student_update'),
    path("student_delete/<int:pk>/", StudentDelete.as_view(), name='student_delete'),
    path("student_detail/<int:pk>/", StudentDetail.as_view(), name='student_detail'),
    path("login/", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path('upload_file/', views.upload_students_excel, name='upload_file'),
    path('download_students/', views.download_students_excel, name='download_students'),
    path('send_email_out/', views.send_email, name='send_email_out'),
    path('api/', include(router.urls))

]

gradebook/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
class Semester(models.Model):
    year = models.PositiveIntegerField()
    semester_number = models.PositiveIntegerField()

    class Meta:
        unique_together = ('year', 'semester_number',)
        ordering = ('-year', '-semester_number',)

    def __str__(self):
        return f"{self.get_semester_display()} {self.year}"

    def get_semester_display(self):
        if self.semester_number == 1:
            return "1st Semester"
        elif self.semester_number == 2:
            return "2nd Semester"
        elif self.semester_number == 3:
            return "Summer Term"
        else:
            return f"{self.semester_number}th Semester"


class Course(models.Model):
    course_code = models.CharField(max_length=20, unique=True)
    course_name = models.CharField(max_length=100)
    semesters = models.ManyToManyField('Semester')

    def __str__(self):
        return f"{self.course_code} - {self.course_name}"

class Lecturer(models.Model):
    staff_ID = models.CharField(max_length=20, unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    courses = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    dob = models.DateField(null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='lecturer')

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.staff_ID})"

class Class(models.Model):
    class_number = models.CharField(max_length=20)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lecturer = models.ForeignKey(Lecturer, on_delete=models.CASCADE)

    def __str__(self):
        return f"Class {self.class_number} ({self.course.course_code}, " \
               f"{self.semester.year} {self.semester.semester_number})"
class Student(models.Model):
    student_ID = models.PositiveIntegerField()
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    dob = models.DateField(null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='student')

    def __str__(self):
        return f'Student: {self.first_name} {self.last_name}'

class StudentEnrollment(models.Model):
    student_ID = models.ForeignKey('Student', on_delete=models.CASCADE)
    class_enrolled = models.ForeignKey('Class', on_delete=models.CASCADE)
    grade = models.PositiveIntegerField(default=0, null=True, blank=True)
    enroll_time = models.DateTimeField(auto_now_add=True)
    grade_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.student_ID} - {self.class_enrolled} - Grade: {self.grade}"

gradebook/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

gradebook/views.py
import csv
from datetime import datetime
import uuid
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
import pandas as pd
from django.core.mail import send_mail
from openpyxl.workbook.workbook import Workbook
from rest_framework import viewsets
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .forms import LoginForm
from .models import Student, StudentEnrollment, Lecturer, Class, Semester, Course
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .serializer import StudentEnrollmentSerializer, UserSerializer


# Create your views here.
def index(request):
    return render(request, 'index.html', {
        'students': Student.objects.all()
    })


def student_detail(request, id):
    student = get_object_or_404(Student, pk=id)
    return render(request, 'student_list.html', {'student': student})


class SemesterList(ListView):
    model = Semester
    template_name = "Semester_List.html"


class SemesterCreate(CreateView):
    model = Semester
    template_name = "Semester_Create.html"
    fields = "__all__"
    success_url = reverse_lazy("semester_list")


class SemesterUpdate(UpdateView):
    model = Semester
    template_name = "Semester_Update.html"
    fields = "__all__"
    success_url = reverse_lazy("semester_list")


class SemesterDetail(DetailView):
    model = Semester
    template_name = "Semester_Detail.html"

class SemesterDelete(DeleteView):
    model = Semester
    template_name = "Semester_Delete.html"
    success_url = reverse_lazy("semester_list")


class CourseList(ListView):
    model = Course
    template_name = "Course_List.html"


class CourseCreate(CreateView):
    model = Course
    template_name = "Course_Create.html"
    fields = "__all__"
    success_url = reverse_lazy("course_list")


class CourseUpdate(UpdateView):
    model = Course
    template_name = "Course_Update.html"
    fields = "__all__"
    success_url = reverse_lazy("course_list")


class CourseDetail(DetailView):
    model = Course
    template_name = "Course_Detail.html"


class CourseDelete(DeleteView):
    model = Course
    template_name = "Course_Delete.html"
    success_url = reverse_lazy("course_list")


class LecturerList(ListView):
    model = Lecturer
    template_name = "Lecturer_List.html"


class LecturerCreate(CreateView):
    model = Lecturer
    template_name = "Lecturer_Create.html"
    fields = "__all__"
    success_url = reverse_lazy("lecturer_list")


class LecturerUpdate(UpdateView):
    model = Lecturer
    template_name = "Lecturer_Update.html"
    fields = "__all__"
    success_url = reverse_lazy("lecturer_list")


class LecturerDetail(DetailView):
    model = Lecturer
    template_name = "Lecturer_Detail.html"


class LecturerDelete(DeleteView):
    model = Lecturer
    template_name = "Lecturer_Delete.html"
    success_url = reverse_lazy("lecturer_list")


class ClassList(ListView):
    model = Class
    template_name = "Class_List.html"


class ClassCreate(CreateView):
    model = Class
    template_name = "Class_Create.html"
    fields = "__all__"
    success_url = reverse_lazy("class_list")


class ClassUpdate(UpdateView):
    model = Class
    template_name = "Class_Update.html"
    fields = "__all__"
    success_url = reverse_lazy("class_list")


class ClassDetail(DetailView):
    model = Class
    template_name = "Class_Detail.html"


class ClassDelete(DeleteView):
    model = Class
    template_name = "Class_Delete.html"
    success_url = reverse_lazy("class_list")


class StudentList(ListView):
    model = Student
    template_name = "Student_List.html"
    context_object_name = 'students'


class StudentCreate(CreateView):
    model = Student
    template_name = "Student_Create.html"
    fields = "__all__"
    success_url = reverse_lazy("student_list")


class StudentUpdate(UpdateView):
    model = Student
    template_name = "Student_Update.html"
    fields = "__all__"
    success_url = reverse_lazy("student_list")

    def form_valid(self, form):
        if not self.request.user.is_superuser:
            student_id = form.cleaned_data['student_ID']
            student_enrollment = StudentEnrollment.objects.get(student_ID=student_id)
            student_enrollment.grade = form.cleaned_data['grade']
            student_enrollment.save()
        return super().form_valid(form)


class StudentDetail(DetailView):
    model = Student
    template_name = "Student_Detail.html"


class StudentDelete(DeleteView):
    model = Student
    template_name = "Student_Delete.html"
    success_url = reverse_lazy("student_list")


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Authenticate user
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                form.add_error(None, 'Invalid username or password.')
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('index')


def download_students_excel(request):
    students = Student.objects.all()
    df = pd.DataFrame(list(students.values()))
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=students.xlsx'
    df.to_excel(response, index=False)
    return response


def upload_students_excel(request):
    if request.method == 'POST':
        file = request.FILES['file']
        if not file.name.endswith('.xlsx'):
            messages.error(request, 'File is not in Excel format')
            return render(request, 'upload_file.html')

        df = pd.read_excel(file)
        for index, row in df.iterrows():
            student_id = int(row['Student ID'])
            first_name = str(row['First Name'])
            last_name = str(row['Last Name'])
            dob_str = str(row['DOB'])
            dob = datetime.strptime(dob_str.split(' ')[0], '%Y-%m-%d').date()
            email = str(row['email'])

            username = email
            while User.objects.filter(username=username).exists():
                username = email + '_' + str(uuid.uuid4())[:8]  # Append a unique identifier to the username

            user = User.objects.create_user(username=username, email=email)
            student = Student.objects.create(
                student_ID=student_id,
                first_name=first_name,
                last_name=last_name,
                email=email,
                dob=dob,
                user=user
            )

        messages.success(request, 'Students uploaded successfully')
        return render(request, 'upload_file.html')

    return render(request, 'upload_file.html')


def download_students_excel(request):
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename="students.xlsx"'

    wb = Workbook()
    ws = wb.active
    ws.append(['Student ID', 'First Name', 'Last Name', 'DOB'])

    students = Student.objects.all()
    for student in students:
        ws.append([student.student_ID, student.first_name, student.last_name, student.dob.strftime('%Y-%m-%d')])

    wb.save(response)
    return response

def send_email(request):
    if request.method == 'POST':
        subject = request.POST.get('subject')
        body = request.POST.get('body')
        from_email = request.POST.get('from_email')
        to_email = request.POST.get('to_email')

        # Send email
        send_mail(subject, body, from_email, [to_email])
        email_sent = True
    else:
        email_sent = False

    return render(request, 'send_email_out.html', {'email_sent': email_sent})


class StudentEnrollmentViewSet(viewsets.ModelViewSet):
    queryset = StudentEnrollment.objects.all()
    serializer_class = StudentEnrollmentSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

gradebook/templates/Class_Delete.html
{% extends "base.html" %}
{% block title %}
Delete Class
{% endblock %}

{% block content %}
    <p>Are you sure to delete?</p>
    <form method="post">
    {% csrf_token %}
    <button class="btn btn-danger">Delete</button>
    </form>

{% endblock %}

gradebook/templates/Course_Create.html
{% extends "base.html" %}
{% block title %}
Create Course
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary">Create</button>
    </form>

{% endblock %}

gradebook/templates/Course_Detail.html
{% extends "base.html" %}
{% block title %}
Course {{ course.course_code }}
{% endblock %}

{% block content %}
    {{ course.course_code }} {{ course.course_name }} {{ course.semesters }} </br>
{% endblock %}

gradebook/templates/Course_Update.html
{% extends "base.html" %}
{% block title %}
Update Course
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-warning">Update</button>
    </form>

{% endblock %}

gradebook/templates/Lecturer_Create.html
{% extends "base.html" %}
{% block title %}
Create Lecturer
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary">Create</button>
    </form>

{% endblock %}

gradebook/templates/Lecturer_Update.html
{% extends "base.html" %}
{% block title %}
Update Lecturer
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-warning">Update</button>
    </form>

{% endblock %}

gradebook/templates/Student_Delete.html
{% extends "base.html" %}
{% block title %}
Delete Student
{% endblock %}

{% block content %}
    <p>Are you sure you want to delete this student?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'student_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

gradebook/templates/Student_Detail.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div class="container-fluid">
    <h3 class="m-4">All Students</h3>
    <div class="row">
        <div class="col-12">
            {% if students %}
            <div class="card bg-light ms-4 me-4 mb-4">
                <div class="card-header">
                    <i class="fa-solid fa-list"></i> Student Record
                </div>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">Student ID</th>
                                        <th scope="col">First Name</th>
                                        <th scope="col">Last Name</th>
                                        <th scope="col">DOB</th>
                                        <th scope="col">Grade</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for student in students %}
                                    <tr>
                                        <td>{{ student.student_ID }}</td>
                                        <td>{{ student.first_name }}</td>
                                        <td>{{ student.last_name }}</td>
                                        <td>{{ student.dob }}</td>
                                        <td>
                                            {% if student.studentenrollment_set.all %}
                                                {% for enrollment in student.studentenrollment_set.all %}
                                                    {{ enrollment.grade }}
                                                {% endfor %}
                                            {% else %}
                                                N/A
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="{% url 'student_update' student.id %}" class="btn btn-primary me-1">
                                                Update
                                            </a>
                                            <a href="{% url 'student_delete' student.id %}" class="btn btn-danger me-1">
                                                Delete
                                            </a>
                                            <button type="button" class="btn btn-success me-1" data-bs-toggle="modal" data-bs-target="#myModal{{ student.id }}">
                                                Inspect
                                            </button>
                                            <div class="modal" id="myModal{{ student.id }}" tabindex="-1" aria-labelledby="myModalLabel{{ student.id }}" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="myModalLabel{{ student.id }}">Student: {{ student.first_name }} {{ student.last_name }}</h5>
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <ul class="modal-body">
                                                                <li>First Name : <strong>{{ student.first_name }}</strong></li>
                                                                <li>Last Name : <strong>{{ student.last_name }}</strong></li>
                                                                <li>Email: <strong>{{ student.email }}</strong></li>
                                                                <li>ID: <strong>{{ student.student_ID }}</strong></li>
                                                                <li>DOB: <strong>{{ student.dob }}</strong></li>
                                                                <br>
                                                                {% if student.studentenrollment_set.all %}
                                                                    {% for enrollment in student.studentenrollment_set.all %}
                                                                        <li>Grade: <strong>{{ enrollment.grade }}</strong></li>
                                                                    {% endfor %}
                                                                {% endif %}
                                                            </ul>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
            {% else %}
            <h5>No record</h5>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

gradebook/templates/Student_List.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div class="container-fluid">
    <h3 class="m-4">All Students</h3>
    <div class="row">
        <div class="col-12">
            {% if students %}
            <div class="card bg-light ms-4 me-4 mb-4">
                <div class="card-header">
                    <i class="fa-solid fa-list"></i> Student Record
                </div>
                <div class="card-body">
                    <p class="card-text">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">Student ID</th>
                                        <th scope="col">First Name</th>
                                        <th scope="col">Last Name</th>
                                        <th scope="col">DOB</th>
                                        <th scope="col">Grade</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for student in students %}
                                    <tr>
                                        <td>{{ student.student_ID }}</td>
                                        <td>{{ student.first_name }}</td>
                                        <td>{{ student.last_name }}</td>
                                        <td>{{ student.dob }}</td>
                                        <td>
                                            {% if student.studentenrollment_set.all %}
                                                {% for enrollment in student.studentenrollment_set.all %}
                                                    {{ enrollment.grade }}
                                                {% endfor %}
                                            {% else %}
                                                N/A
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="{% url 'student_update' student.id %}" class="btn btn-primary me-1">
                                                Update
                                            </a>
                                            <a href="{% url 'student_delete' student.id %}" class="btn btn-danger me-1">
                                                Delete
                                            </a>
                                            <button type="button" class="btn btn-success me-1" data-bs-toggle="modal" data-bs-target="#myModal{{ student.id }}">
                                                Inspect
                                            </button>
                                            <div class="modal" id="myModal{{ student.id }}" tabindex="-1" aria-labelledby="myModalLabel{{ student.id }}" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="myModalLabel{{ student.id }}">Student: {{ student.first_name }} {{ student.last_name }}</h5>
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <ul class="modal-body">
                                                                <li>First Name : <strong>{{ student.first_name }}</strong></li>
                                                                <li>Last Name : <strong>{{ student.last_name }}</strong></li>
                                                                <li>Email: <strong>{{ student.email }}</strong></li>
                                                                <li>ID: <strong>{{ student.student_ID }}</strong></li>
                                                                <li>DOB: <strong>{{ student.dob }}</strong></li>
                                                                <br>
                                                                {% if student.studentenrollment_set.all %}
                                                                    {% for enrollment in student.studentenrollment_set.all %}
                                                                        <li>Grade: <strong>{{ enrollment.grade }}</strong></li>
                                                                    {% endfor %}
                                                                {% endif %}
                                                            </ul>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </p>
                </div>
            </div>
            {% else %}
            <h5>No record</h5>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

gradebook/templates/Student_Update.html
{% extends "base.html" %}
{% block title %}
Update Student
{% endblock %}

{% block content %}
    <h2>Update Student</h2>
    {% if not user.is_superuser %}
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_grade" class="form-label">Grade</label>
                <input type="text" class="form-control" id="id_grade" name="grade" value="{{ student.grade }}">
            </div>
            <button type="submit" class="btn btn-primary">Update Grade</button>

        </form>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    {% endif %}
{% endblock %}

gradebook/templates/index.html
{% extends 'base.html' %}

{% block title %}
Gradebook Home
{% endblock %}

{% block content %}
<div class="container-fluid">
    <h3 class="m-4">Gradebook Home</h3>
    <div class="row">
        <div class="col-12">
            <div class="card bg-light ms-4 me-4 mb-4">
                <div class="card-header">
                    <i class="fa-solid fa-list"></i>
                </div>
                <div class="card-body">
                    <p>Welcome to the Gradebook Home. Choose an option from the navigation above to get started.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}